version: '3.1'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - temaspt

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"

  temaspt:
    build: ./TemaSPT
    working_dir: /TemaSPT
    volumes:
      - ./TemaSPT:/TemaSPT
      - ~/.m2:/root/.m2
    expose:
      - 8080
    command: mvn clean spring-boot:run
    depends_on:
      - mongo